//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Satis
    {
        public int SatisId { get; set; }

        [Required(ErrorMessage="Ürün Boþ Geçilemez!")]
        public Nullable<int> Urun { get; set; }
        
        [Required(ErrorMessage ="Müþteri Boþ Geçilemez!")]
        public Nullable<int> Musteri { get; set; }

        [Required(ErrorMessage ="Adet Boþ Geçilemez!")]
        public Nullable<byte> Adet { get; set; }

        [Required(ErrorMessage ="Fiyat Boþ Geçilemez!")]
        public Nullable<decimal> Fiyat { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
